services:
  - type: web
    name: fundraising-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd fundraising-backend && npm install
    startCommand: cd fundraising-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
